import XCTest
@testable import TRAVEL_GUIDED_TOUR

/// Holds `TourEmbeddingStore` to what `build-embeddings.py` actually computes.
///
/// WHY THIS FILE EXISTS
/// --------------------
/// Semantic search has three seams where the phone can silently disagree with
/// the server. Two already have alarms: `TokenizerParityTests` pins the token
/// ids, and `scripts/verify-coreml-parity.py` pins the model on a real Mac.
/// This is the third — the **sidecar format and the scoring**.
///
/// `tour_scores` in `build-embeddings.py` carries the instruction in its own
/// docstring: *"THIS IS THE FUNCTION THE APP RE-IMPLEMENTS… keep this in step
/// with the Swift side."* A drift there produces a slightly different order,
/// forever, with no crash and no log line.
///
/// 🔴 THE FIXTURE IS A REAL SIDECAR. `scripts/dump-ranking-fixture.py` samples
/// the live catalog, runs the real model, and writes it with the real
/// `write_embeddings` — so the offsets, the int8 quantization and the
/// multi-chunk entries are genuine rather than my idea of them. The expected
/// scores are Python's, computed against the **dequantized** chunks, because
/// that is what Swift reads out of the file.
///
/// ⚠️ IF THIS FAILS, DO NOT REGENERATE THE FIXTURE TO MAKE IT PASS. The fixture
/// is the server's answer. A failure means the Swift side drifted from it.
final class RankingParityTests: XCTestCase {

    private struct Fixture: Decodable {
        struct Expected: Decodable {
            let id: String
            let score: Float
            let title: String
        }
        struct Case: Decodable {
            let query: String
            let queryVector: [Float]
            let expected: [Expected]
        }
        let model: String
        let dims: Int
        let bestChunkWeight: Float
        let quantScale: Float
        let floor: Float
        let limit: Int
        let entries: Int
        let chunks: Int
        let cases: [Case]
    }

    /// 🔴 THROWS RATHER THAN SKIPPING. A missing fixture must fail the build,
    /// not quietly turn this suite into a no-op that reports green.
    private func loadFixture() throws -> (Fixture, Data) {
        let bundle = Bundle(for: RankingParityTests.self)
        func resource(_ name: String, _ ext: String) throws -> URL {
            try XCTUnwrap(
                bundle.url(forResource: name, withExtension: ext)
                    ?? Bundle.main.url(forResource: name, withExtension: ext),
                """
                \(name).\(ext) is not in the test bundle. Both halves are \
                generated by `python3 scripts/dump-ranking-fixture.py` and must \
                be copied as test resources — without them this suite proves \
                nothing.
                """
            )
        }
        let json = try JSONDecoder().decode(
            Fixture.self, from: Data(contentsOf: try resource("ranking-parity", "json"))
        )
        return (json, try Data(contentsOf: try resource("ranking-parity", "bin")))
    }

    // MARK: - The format

    func testHeaderParsesAndAgreesWithPython() throws {
        let (fixture, binary) = try loadFixture()
        let index = try TourEmbeddingStore.parse(binary)

        XCTAssertEqual(index.modelID, fixture.model,
                       "the sidecar names a different model than the fixture")
        XCTAssertEqual(index.dims, fixture.dims)
        XCTAssertEqual(index.tourIDs.count, fixture.entries)
        // n+1 offsets: the last is the total, so no special case for the final
        // entry when deriving a chunk count.
        XCTAssertEqual(index.chunkOffsets.count, fixture.entries + 1)
        XCTAssertEqual(index.chunkOffsets.last, fixture.chunks)
        XCTAssertEqual(index.chunks.count, fixture.chunks * fixture.dims)
    }

    /// The fixture must actually contain what it claims to exercise. A sample
    /// where every entry happened to fit in one chunk would test the offset
    /// arithmetic not at all while looking like it did.
    func testFixtureContainsMultiChunkEntries() throws {
        let (_, binary) = try loadFixture()
        let index = try TourEmbeddingStore.parse(binary)
        let multi = (0..<index.tourIDs.count).filter {
            index.chunkOffsets[$0 + 1] - index.chunkOffsets[$0] > 1
        }
        XCTAssertFalse(multi.isEmpty,
                       "no entry in the fixture spans more than one chunk, so "
                       + "the best-chunk/mean blend is untested")
    }

    func testDequantizedVectorsAreUnitLength() throws {
        let (fixture, binary) = try loadFixture()
        let index = try TourEmbeddingStore.parse(binary)
        for chunk in 0..<(index.chunks.count / fixture.dims) {
            var sum: Float = 0
            for component in 0..<fixture.dims {
                let value = index.chunks[chunk * fixture.dims + component]
                XCTAssertTrue(value.isFinite, "non-finite value in chunk \(chunk)")
                sum += value * value
            }
            // `>=` negated, not `<`: a NaN length must fail rather than pass.
            XCTAssertTrue(abs(sum.squareRoot() - 1) <= 1e-4,
                          "chunk \(chunk) has length \(sum.squareRoot())")
        }
    }

    // MARK: - Rejection

    func testRefusesAFileThatIsNotASidecar() {
        XCTAssertThrowsError(try TourEmbeddingStore.parse(Data("not a sidecar".utf8)))
    }

    /// 🔴 A truncated download is the realistic corruption, and the dangerous
    /// one: without a length check the reader walks off the end of the data and
    /// ranks the catalog from whatever it finds.
    func testRefusesATruncatedFile() throws {
        let (_, binary) = try loadFixture()
        XCTAssertThrowsError(
            try TourEmbeddingStore.parse(Data(binary.prefix(binary.count - 64)))
        ) { error in
            XCTAssertTrue("\(error)".contains("expected"),
                          "should say the file is the wrong length, said: \(error)")
        }
    }

    /// A sidecar built with a different model is the invisible failure this
    /// whole header exists to catch: every vector plausible, every ranking
    /// wrong, nothing logged.
    func testRefusesAForeignModelID() throws {
        let (_, binary) = try loadFixture()
        var bytes = [UInt8](binary)
        // The model id lives at offset 32, 64 bytes, null-padded.
        for (offset, byte) in Array("some-other/model".utf8).enumerated() {
            bytes[32 + offset] = byte
        }
        XCTAssertThrowsError(try TourEmbeddingStore.parse(Data(bytes))) { error in
            XCTAssertTrue("\(error)".contains("some-other/model"),
                          "should name the offending model, said: \(error)")
        }
    }

    // MARK: - 🔴 The scoring itself

    func testRanksExactlyAsPythonDoes() async throws {
        let (fixture, binary) = try loadFixture()
        XCTAssertEqual(TourEmbeddingStore.bestChunkWeight, fixture.bestChunkWeight,
                       "the blend weight has drifted from build-embeddings.py")

        let store = TourEmbeddingStore()
        try await store.load(binary)

        for testCase in fixture.cases {
            let matches = try await store.search(
                testCase.queryVector, limit: fixture.limit, floor: fixture.floor
            )
            // ⚠️ Compared case-insensitively on purpose: Tours.json stores
            // link-pin ids UPPERCASE while `UUID.uuidString` is uppercase and
            // Python's json carries whatever the catalog had. Case is not part
            // of the identity, and a naive comparison would report every pin
            // as a mismatch.
            XCTAssertEqual(
                matches.map { $0.tourID.uuidString.lowercased() },
                testCase.expected.map { $0.id.lowercased() },
                "different order for \(testCase.query)"
            )
            for (match, expected) in zip(matches, testCase.expected) {
                // Both sides do the same arithmetic on the same dequantized
                // numbers, so this is float summation order, not quantization.
                XCTAssertEqual(match.score, expected.score, accuracy: 1e-4,
                               "\(expected.title): \(match.score) vs \(expected.score)")
            }
        }
    }
}
