import XCTest
@testable import TRAVEL_GUIDED_TOUR

/// Holds `WordPieceTokenizer` to what the Python pipeline actually does.
///
/// WHY THIS FILE EXISTS
/// --------------------
/// Semantic search turns a typed query into a vector and compares it against
/// vectors computed offline by `scripts/build-embeddings.py`. Those two are
/// only comparable if the query is tokenized **identically**, and there is no
/// Apple framework for BERT WordPiece — so `WordPieceTokenizer` is a
/// hand-written reimplementation of `all-MiniLM-L6-v2`'s `tokenizer.json`.
///
/// 🔴 A WRONG TOKENIZER NEVER CRASHES. It returns slightly different ids, so a
/// slightly different vector, so results that look plausible and are worse —
/// with no exception, no log line and no failing build. Every silent-failure
/// incident in `docs/lessons.md` has this shape. This file is the alarm.
///
/// The expectations are not hand-written. `scripts/dump-tokenizer-fixture.py`
/// runs the REAL HuggingFace tokenizer over 61 strings and pins its output;
/// the strings are drawn from the live catalog wherever possible, because a
/// fixture invented from imagination tests the imagination.
///
/// ⚠️ IF THIS FAILS, DO NOT "FIX" THE FIXTURE. The fixture is the truth — it
/// came from the tokenizer that produced every vector we ship. A failure means
/// the Swift side drifted, or the model changed and the whole index is stale.
final class TokenizerParityTests: XCTestCase {

    // MARK: - Fixture

    private struct Fixture: Decodable {
        struct Case: Decodable {
            let text: String
            let ids: [Int32]
            let tokens: [String]
        }
        let model: String
        let vocabSize: Int
        let specialTokens: [String: Int32]
        let maxInputCharsPerWord: Int
        let cases: [Case]
    }

    /// 🔴 THROWS RATHER THAN SKIPPING, DELIBERATELY. An `XCTSkip` here would
    /// turn "the fixture never made it into the test bundle" into a green
    /// build — a check that cannot run reporting a pass, which is the exact
    /// trap CLAUDE.md § "Reading a check's result" is about.
    private func loadFixture() throws -> Fixture {
        let bundle = Bundle(for: TokenizerParityTests.self)
        let url = try XCTUnwrap(
            bundle.url(forResource: "tokenizer-parity", withExtension: "json")
                ?? Bundle.main.url(forResource: "tokenizer-parity", withExtension: "json"),
            """
            tokenizer-parity.json is not in the test bundle. It is generated by \
            `python3 scripts/dump-tokenizer-fixture.py` and must be copied as a \
            test resource — without it this suite proves nothing.
            """
        )
        return try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
    }

    /// The same `vocab.txt` the app ships, for the same reason.
    private func loadTokenizer() throws -> WordPieceTokenizer {
        let url = try XCTUnwrap(
            Bundle.main.url(forResource: "vocab", withExtension: "txt")
                ?? Bundle(for: TokenizerParityTests.self)
                    .url(forResource: "vocab", withExtension: "txt"),
            """
            vocab.txt is not in the bundle. It is generated by \
            `python3 scripts/export-tokenizer-vocab.py` from the model's own \
            tokenizer.json and ships in Resources/.
            """
        )
        return try WordPieceTokenizer(
            vocabularyText: String(contentsOf: url, encoding: .utf8)
        )
    }

    // MARK: - The vocabulary is the one the vectors were built from

    func testVocabularyMatchesTheFixture() throws {
        let fixture = try loadFixture()
        let tokenizer = try loadTokenizer()

        XCTAssertEqual(
            tokenizer.vocabularySize, fixture.vocabSize,
            "vocab.txt has \(tokenizer.vocabularySize) tokens, the model has \(fixture.vocabSize) — "
            + "re-run scripts/export-tokenizer-vocab.py"
        )
        // Special-token ids are pinned because everything downstream indexes by
        // them. [UNK] landing on the wrong id would mis-embed every unmatched
        // word rather than failing.
        XCTAssertEqual(tokenizer.unknownID, fixture.specialTokens["[UNK]"])
        XCTAssertEqual(tokenizer.classificationID, fixture.specialTokens["[CLS]"])
        XCTAssertEqual(tokenizer.separatorID, fixture.specialTokens["[SEP]"])
        XCTAssertEqual(tokenizer.paddingID, fixture.specialTokens["[PAD]"])
        XCTAssertEqual(WordPieceTokenizer.maxInputCharsPerWord, fixture.maxInputCharsPerWord)
    }

    // MARK: - 🔴 The one that matters

    func testEveryFixtureCaseTokenizesIdentically() throws {
        let fixture = try loadFixture()
        let tokenizer = try loadTokenizer()

        XCTAssertGreaterThan(
            fixture.cases.count, 50,
            "the fixture shrank — it is meant to carry every awkward case, not a sample"
        )

        var mismatches: [String] = []
        for testCase in fixture.cases {
            let produced = tokenizer.encode(testCase.text)
            guard produced != testCase.ids else { continue }
            // The Python `tokens` are carried purely so a failure is readable:
            // a list of integers says nothing about WHICH rule drifted.
            mismatches.append(
                """
                • \(String(reflecting: testCase.text.prefix(60)))
                    expected \(testCase.ids)
                        i.e. \(testCase.tokens)
                    got      \(produced)
                """
            )
        }

        XCTAssertTrue(
            mismatches.isEmpty,
            """
            \(mismatches.count) of \(fixture.cases.count) cases tokenize differently \
            from the Python pipeline that built every vector we ship.

            DO NOT regenerate the fixture to make this pass. Either
            WordPieceTokenizer drifted, or the model changed — and if the model \
            changed, the whole embeddings index is stale too.

            \(mismatches.joined(separator: "\n"))
            """
        )
    }

    // MARK: - The rules most likely to be got wrong, named individually
    //
    // The bulk test above would catch all of these. They are separate so a
    // failure says WHICH rule broke instead of "37 cases differ".

    /// CJK ideographs are space-padded into single tokens; kana and Hangul are
    /// not. Getting this backwards is invisible in English and wrong for the
    /// 281 catalog titles carrying CJK.
    func testCJKIdeographsArePaddedButKanaIsNot() throws {
        XCTAssertTrue(WordPieceTokenizer.isCJKIdeograph("東"))
        XCTAssertTrue(WordPieceTokenizer.isCJKIdeograph("京"))
        XCTAssertFalse(WordPieceTokenizer.isCJKIdeograph("タ"), "katakana is not an ideograph")
        XCTAssertFalse(WordPieceTokenizer.isCJKIdeograph("ひ"), "hiragana is not an ideograph")
        XCTAssertFalse(WordPieceTokenizer.isCJKIdeograph("아"), "hangul is not an ideograph")
        XCTAssertFalse(WordPieceTokenizer.isCJKIdeograph("ก"), "thai is not an ideograph")

        // The observable consequence: 東京 becomes two standalone tokens while
        // タワー stays one word for WordPiece to split with ## continuations.
        XCTAssertEqual(WordPieceTokenizer.preTokenize(WordPieceTokenizer.normalize("東京タワー")),
                       ["東", "京", "タワー"])
    }

    /// `strip_accents` is null, which follows `lowercase` — so accents ARE
    /// stripped. Reading null as "off" is the obvious misreading.
    func testAccentsAreStrippedAndTextIsLowercased() {
        XCTAssertEqual(WordPieceTokenizer.normalize("Café"), "cafe")
        XCTAssertEqual(WordPieceTokenizer.normalize("Gaudí"), "gaudi")
        XCTAssertEqual(WordPieceTokenizer.normalize("ZÜRICH"), "zurich")
    }

    /// BERT splits punctuation into its own tokens, and its notion of
    /// punctuation is wider than `CharacterSet.punctuationCharacters`.
    func testPunctuationSplitsOffAndCoversTheASCIIBlocks() {
        XCTAssertEqual(WordPieceTokenizer.preTokenize(WordPieceTokenizer.normalize("St. Paul's")),
                       ["st", ".", "paul", "'", "s"])
        for symbol in ["+", "<", "=", ">", "$", "^", "`", "|", "~"] {
            XCTAssertTrue(
                WordPieceTokenizer.isPunctuation(Unicode.Scalar(symbol.unicodeScalars.first!)),
                "\(symbol) is punctuation to BERT even though Foundation disagrees"
            )
        }
    }

    /// A word over `max_input_chars_per_word` is ONE `[UNK]`, not a split and
    /// not one per character.
    func testOverlongWordBecomesASingleUnknown() throws {
        let tokenizer = try loadTokenizer()
        XCTAssertEqual(tokenizer.encode(String(repeating: "x", count: 150)),
                       [tokenizer.unknownID])
    }

    /// Empty and whitespace-only input must produce nothing at all — a search
    /// box receives both constantly.
    func testEmptyInputProducesNoTokens() throws {
        let tokenizer = try loadTokenizer()
        XCTAssertEqual(tokenizer.encode(""), [])
        XCTAssertEqual(tokenizer.encode("   "), [])
        XCTAssertEqual(tokenizer.encode("\t\n\r"), [])
    }
}
